---
# Application
app_repo: https://github.com/pravinmishraaws/theepicbook
app_dest: /home/azureuser/epicbook
app_user: azureuser
app_port: 8080
pm2_app_name: epicbook

# Nginx (VM public IP from terraform output)
server_name: 102.133.164.135

# Managed MySQL (values from terraform output)
db_host: epicbook-mysql-tolu01.mysql.database.azure.com
db_name: bookstore
db_user: epicadmin
db_password: "{{ vault_db_password }}"
